config/routes.rb
Rails.application.routes.draw do

  get 'password_resets/new'

  get 'password_resets/edit'

  root 'static_pages#home'
  get 'about' => 'static_pages#about'
  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    A webapp by
    <a
      class="logo-wrapper"
      target="_blank"
      rel="noopener noreferrer"
      href="https://ls-portfolio.surge.sh"
    >
      <%= image_tag("Logo_ls_1.png", :alt => "ls", :class => 'styled-logo-1') %>
      <%= image_tag("Logo_ls_2.png", :alt => "ls", :class => 'styled-logo-2') %>
    </a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About", about_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
            <%= link_to "Micropost App", root_path, id: "logo" %>
            <nav>
      		<ul class="nav navbar-nav navbar-right">
                  <% if logged_in? %>
                        <li><%= link_to "Users", users_path %></li>
                        <li class="dropdown">
                              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Account <b class="caret"></b></a>
                              <ul class="dropdown-menu">
                                    <li><%= link_to "Profile", current_user %></li>
                                    <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                                    <li class="divider"></li>
                                    <li><%= link_to "log out", logout_path, method: "delete" %></li>
                              </ul>
                        </li>
                  <% else %>
                        <li><%= link_to "log in", login_path %></li>
                  <% end %>
      		</ul>
      	</nav>
      </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
	<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  	<title><%= full_title(yield(:title)) %></title>
	  	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => 	true %>
	  	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	  	<%= csrf_meta_tags %>
	  	<%= render 'layouts/shim' %>
	</head>
	<body>
		<%= render 'layouts/header' %>
    	<div class="container">
    		<% flash.each do |message_type, message| %>
    			<%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
    		<% end %>
      		<%= yield %>
      		<%= render 'layouts/footer' %>
      		<%= debug(params) if Rails.env.development? %>
		</div>
	</body>
</html>